### Imports
Event accumulator to fetch data from a saved checkpoint file

In [1]:
from tensorboard.backend.event_processing.event_accumulator import EventAccumulator
import numpy as np
import matplotlib.pyplot as plt
%matplotlib notebook

In [2]:
event_file = '../train/log_002'
eacc = EventAccumulator(event_file)
eacc.Reload()
eacc.Tags()

INFO:tensorflow:No path found after ../train/log_002/events.out.tfevents.1506958680.Alexs-MacBook-Pro.local


{'audio': [],
 'distributions': [],
 'graph': True,
 'histograms': [],
 'images': [],
 'meta_graph': True,
 'run_metadata': [],
 'scalars': ['Input_pipeline/input_producer/fraction_of_32_full',
  'XOR_model/train/error_summary'],
 'tensors': ['XOR_model/input_patterns/data_summary',
  'XOR_model/pattern_labels/data_summary',
  'XOR_model/hidden_layer/weights/params_summary',
  'XOR_model/hidden_layer/biases/params_summary',
  'XOR_model/hidden_layer/net_input/data_summary',
  'XOR_model/hidden_layer/activations/data_summary',
  'XOR_model/output_layer/weights/params_summary',
  'XOR_model/output_layer/biases/params_summary',
  'XOR_model/output_layer/net_input/data_summary',
  'XOR_model/output_layer/activations/data_summary',
  'XOR_model/train/target_patterns/data_summary']}

In [4]:
np.set_printoptions(precision=3)

model_name = 'XOR_model'
layer_name = 'output_layer'
data_type = np.float32
for tt in eacc.Tags()['tensors']:
    fetch = '/'.join([model_name, layer_name])
    if fetch in tt:
        print(tt)
        for te in eacc.Tensors(tt):
            shape = [i.size for i in te.tensor_proto.tensor_shape.dim]
            binary_tensor = te.tensor_proto.tensor_content
            deci_tensor  = np.fromstring(binary_tensor, dtype=np.float32).reshape(shape)
            print('training step: {}\n tensor shape: {}\n{}\n'.format(te.step, shape, deci_tensor))
    if 'input_patterns' in tt or 'target_patterns' in tt:
        print(tt)
        for te in eacc.Tensors(tt):
            shape = [i.size for i in te.tensor_proto.tensor_shape.dim]
            binary_tensor = te.tensor_proto.tensor_content
            deci_tensor  = np.fromstring(binary_tensor, dtype=np.float32).reshape(shape)
            print('training step: {}\n tensor shape: {}\n{}\n'.format(te.step, shape, deci_tensor))
    if 'input_patterns' in tt or 'target_patterns' in tt:
        print(tt)
        for te in eacc.Tensors(tt):
            print(te)
#             shape = [i.size for i in te.tensor_proto.tensor_shape.dim]
#             binary_tensor = te.tensor_proto.tensor_content
#             deci_tensor  = np.fromstring(binary_tensor, dtype=np.float32).reshape(shape)
#             print('training step: {}\n tensor shape: {}\n{}\n'.format(te.step, shape, deci_tensor))


XOR_model/input_patterns/data_summary
training step: 0
 tensor shape: [4, 2]
[[ 0.  0.]
 [ 0.  1.]
 [ 1.  0.]
 [ 1.  1.]]

training step: 30
 tensor shape: [4, 2]
[[ 0.  0.]
 [ 0.  1.]
 [ 1.  0.]
 [ 1.  1.]]

training step: 60
 tensor shape: [4, 2]
[[ 0.  0.]
 [ 0.  1.]
 [ 1.  0.]
 [ 1.  1.]]

training step: 90
 tensor shape: [4, 2]
[[ 0.  0.]
 [ 0.  1.]
 [ 1.  0.]
 [ 1.  1.]]

training step: 120
 tensor shape: [4, 2]
[[ 0.  0.]
 [ 0.  1.]
 [ 1.  0.]
 [ 1.  1.]]

training step: 150
 tensor shape: [4, 2]
[[ 0.  0.]
 [ 0.  1.]
 [ 1.  0.]
 [ 1.  1.]]

training step: 240
 tensor shape: [4, 2]
[[ 0.  0.]
 [ 0.  1.]
 [ 1.  0.]
 [ 1.  1.]]

training step: 270
 tensor shape: [4, 2]
[[ 0.  0.]
 [ 0.  1.]
 [ 1.  0.]
 [ 1.  1.]]

training step: 300
 tensor shape: [4, 2]
[[ 0.  0.]
 [ 0.  1.]
 [ 1.  0.]
 [ 1.  1.]]

training step: 317
 tensor shape: [4, 2]
[[ 0.  0.]
 [ 0.  1.]
 [ 1.  0.]
 [ 1.  1.]]

XOR_model/input_patterns/data_summary
TensorEvent(wall_time=1506958680.6840808, step=0, tensor_pr

In [ ]:
def get_event_accumulator(path_to_event_file):
    event_file = path_to_event_file
    eacc = EventAccumulator(event_file)
    eacc.Reload()
    return eacc

def retrieve_array(path_to_event_file, layer_name, tensor_name, data_type=np.float32):
    eacc = get_event_accumulator(path_to_event_file)
    ln = layer_name
    dt = data_type
    for tt in eacc.Tags()['tensors']:
        fetch = '/'.join([layer_name, tensor_name])
        if fetch in tt:
            ra = []
            rs = []
            for te in eacc.Tensors(tt):
                shape = [i.size for i in te.tensor_proto.tensor_shape.dim]
                binary_tensor = te.tensor_proto.tensor_content
                deci_tensor  = np.fromstring(binary_tensor, dtype=dt).reshape(shape)
                ra.append(deci_tensor)
                rs.append(te.step)
    return ra, rs

In [ ]:
retrieve_array(event_file, 'hidden_layer', 'biases')

In [ ]:
retrieve_array(event_file, 'hidden_layer', 'net_input')